#!/usr/bin/env bash
# Copies every Markdown file in the repo into one flat folder (default: markdown/), so the team
# guide, the lessons and the stock SDK notes can be read or handed out together.
#
# The copies are generated. Edit the originals (docs/, README.md, the module readmes)
# and re-run this script; do not edit the files in the output folder.
#
# Lesson files keep their names so the links between lessons still work, and the team guide index
# is placed at README.md inside the folder so "Back to the index" links resolve to it. Files that
# would collide on name are renamed after their source.
set -euo pipefail
cd "$(dirname "$0")/.."
OUT="${1:-markdown}"
rm -rf "$OUT"
mkdir -p "$OUT"

copy() { cp "$1" "$OUT/$2"; printf '%-44s <- %s\n' "$2" "$1" >> "$OUT/INDEX.tmp"; }

: > "$OUT/INDEX.tmp"
for f in docs/0*.md; do copy "$f" "$(basename "$f")"; done
copy docs/README.md README.md
copy README.md REPO-README.md
copy TeamCode/src/main/java/org/firstinspires/ftc/teamcode/readme.md TeamCode-readme.md
copy TeamCode/src/main/res/raw/readme.md TeamCode-res-raw-readme.md
copy FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/readme.md FtcRobotController-samples-readme.md
copy FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/sample_conventions.md FtcRobotController-sample_conventions.md
copy .github/CONTRIBUTING.md GitHub-CONTRIBUTING.md
copy .github/PULL_REQUEST_TEMPLATE.md GitHub-PULL_REQUEST_TEMPLATE.md

{
  echo "# All Markdown in this repository"
  echo
  echo "Generated by \`tools/collect_markdown.sh\`. These are copies: edit the originals listed on the"
  echo "right and re-run the script. Start with \`README.md\` (the team guide index)."
  echo
  echo '```'
  cat "$OUT/INDEX.tmp"
  echo '```'
} > "$OUT/INDEX.md"
rm "$OUT/INDEX.tmp"

# Anything this script does not know about is a sign it needs updating.
expected=$(find . -name '*.md' -not -path './.git/*' -not -path './build/*' -not -path '*/build/*' -not -path "./$OUT/*" -not -path './.gradle/*' | wc -l | tr -d ' ')
copied=$(ls "$OUT"/*.md | grep -vc INDEX.md)
if [ "$expected" != "$copied" ]; then
  echo "warning: repo has $expected .md files but $copied were copied; update this script" >&2
  exit 1
fi
echo "copied $copied files into $OUT/"
